event_inherited();
spr_move = spr_gnome_move;
spr_turn = spr_biggiebag_turn;
spr_stun = spr_biggiebag_stun;
spr_scared = spr_biggiebag_scared;
spr_dead = spr_biggiebag_dead;
attackTimer = 0;
hitbox = false;
hitboxInst = noone;
afterimageBlur = 3;
